	LIST	P=16F628A
	INCLUDE	"P16F628A.INC"
	__CONFIG _XT_OSC & _WDT_OFF & _PWRTE_ON & _MCLRE_ON & _BODEN_OFF & _LVP_OFF & _DATA_CP_OFF & _CP_OFF
	ORG	h'0000'
	CLRF	PORTB	
	BANKSEL	TRISB	
	CLRF	TRISB	
	MOVLW	h'FF'	
	MOVWF	TRISA	
	BANKSEL	PORTB	
	MOVLW	h'07'	 
	MOVWF	CMCON	
BASLA
	MOVF	PORTA,W	
	MOVWF	PORTB	
DONGU
	GOTO	DONGU	
	END		