LIST	P=16F628A
	INCLUDE	"P16F628A.INC"
	__CONFIG _INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_ON & _MCLRE_OFF & _BODEN_OFF & _LVP_OFF & _DATA_CP_OFF & _CP_OFF

	ORG		h'0000'
	CLRF		PORTB		
	BANKSEL	TRISB		
	MOVLW	b'00001000'	
	MOVWF	TRISB		
	MOVLW	b'11110111'	
	MOVWF	TRISA		
	BANKSEL	PORTB		
	MOVLW	h'07'		
	MOVWF	CMCON		
BASLA
	MOVF		PORTA,W		
	MOVWF	PORTB	
	MOVF		PORTB,W		
	MOVWF	PORTA	
	GOTO		BASLA		
	END					
