	LIST	P=16F628A
	INCLUDE	"P16F628A.INC"
	__CONFIG _INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_ON & _MCLRE_ON & _BODEN_OFF & _LVP_OFF & _DATA_CP_OFF & _CP_OFF
	ORG		h'0000'
	CLRF		PORTB		
	BANKSEL	TRISB		
	MOVLW	b'11111110'	
	MOVWF	TRISB		
	MOVLW	b'11111111'	
	MOVWF	TRISA		
	BANKSEL	PORTB		
	MOVLW	h'07'		
	MOVWF	CMCON		
TEST_PORTA
	BTFSS	PORTA,0		
	BCF		PORTB,0		 
	BTFSS	PORTA,4		
	BSF		PORTB,0		 
	GOTO 	TEST_PORTA	
	END