	LIST	P=16F628A
	INCLUDE	"P16F628A.INC"
	__CONFIG _RC_OSC_CLKOUT & _WDT_OFF & _PWRTE_ON & _MCLRE_ON & _BODEN_OFF & _LVP_OFF & _DATA_CP_OFF & _CP_OFF
	CLRF		PORTB
SAYAC	EQU	h'20'		
	BANKSEL	TRISB		
	MOVLW	b'11111110'	
	MOVWF	TRISB		
	MOVLW	b'11111111'	
	MOVWF	TRISA		
	BANKSEL	PORTB		
	MOVLW	h'07'		
	MOVWF	CMCON		
BASLA
	MOVLW	d'10'		
	MOVWF	SAYAC		
TEST
	BTFSC	PORTA, 0		
	GOTO		TEST			
	NOP					
	NOP					
	NOP					
	NOP					
	NOP					
	NOP					
	NOP					
	NOP					
	NOP					
	NOP					
	NOP					
	NOP					
	NOP					
	NOP					
	NOP					
	DECFSZ	SAYAC, F		
	GOTO	TEST				
	BSF	PORTB, 0			
DONGU
	GOTO DONGU
	END