	LIST	P=16F628A
	INCLUDE	"P16F628A.INC"
	__CONFIG _RC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_ON & _MCLRE_ON & _BODEN_OFF & _LVP_OFF & _DATA_CP_OFF & _CP_OFF
SAYAC1	EQU	H'20'		
SAYAC2	EQU	H'21'		
	BANKSEL 	TRISB		
	CLRF		TRISB		
	MOVLW	H'FF'		
	MOVWF	TRISA		
	BANKSEL 	PORTB		
	MOVLW	h'07'		
	MOVWF	CMCON 		
	CLRF		PORTB		
BASLA	
	MOVLW	H'0A'		
	MOVWF	SAYAC1		
TEST
	BTFSC	PORTA,0		
	GOTO		TEST			
	MOVLW	H'20'		
	MOVWF	SAYAC2		
GECIKME					
	NOP					
	NOP					
	NOP				
	DECFSZ	SAYAC2, F		
	GOTO		GECIKME		
AZALT					
	DECFSZ	SAYAC1, F		
	GOTO	YAK				
	GOTO	BASLA			
	MOVF		SAYAC1,W	
	MOVWF	PORTB		
	GOTO		TEST			
	END					
