	LIST	P=16F628A
	INCLUDE	"P16F628A.INC"
	__CONFIG _RC_OSC_CLKOUT & _WDT_OFF & _PWRTE_ON & _MCLRE_ON & _BODEN_OFF & _LVP_OFF & _DATA_CP_OFF & _CP_OFF
	BANKSEL	TRISB		
	CLRF		TRISB		
	BANKSEL	PORTB		
	CLRF		PORTB		
BASLA
	MOVLW	h'04'		
	SUBLW	h'05'		
	MOVF		STATUS, W
	MOVWF	PORTB		
DONGU
	GOTO		DONGU
	END
