	LIST	P=16F628A
	INCLUDE	"P16F628A.INC"
	__CONFIG _RC_OSC_CLKOUT & _WDT_OFF & _PWRTE_ON & _MCLRE_ON & _BODEN_OFF & _LVP_OFF & _DATA_CP_OFF & _CP_OFF
SAYAC	EQU	h'20'	
	BANKSEL	TRISB		
	CLRF		TRISB		
	BANKSEL	PORTB		
	CLRF		PORTB		
BASLA
	CLRF		PORTB		
	CLRF		SAYAC		
TEKRAR
	MOVF		SAYAC, W			
	MOVWF	PORTB		
	INCF		SAYAC, F		
	MOVLW	h'F5'		
	SUBWF	SAYAC, W		
	BTFSS	STATUS, 2		
	GOTO 	TEKRAR		
DONGU
	GOTO		DONGU
	END